# Generated by Django 6.0.1 on 2026-03-28 23:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpsserver',
            options={'ordering': ['status', 'name'], 'verbose_name': 'Прокси-сервер', 'verbose_name_plural': 'Прокси-серверы'},
        ),
        migrations.AddField(
            model_name='activeconnection',
            name='bytes_received',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activeconnection',
            name='bytes_sent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proxytoken',
            name='current_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_connection', to='api.activeconnection'),
        ),
        migrations.AddField(
            model_name='vpsserver',
            name='current_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_connection', to='api.activeconnection', verbose_name='Активное подключение'),
        ),
        migrations.AddField(
            model_name='vpsserver',
            name='current_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using_server', to='api.proxytoken', verbose_name='Текущий токен'),
        ),
        migrations.AlterField(
            model_name='activeconnection',
            name='client_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Информация о клиенте'),
        ),
        migrations.AlterField(
            model_name='activeconnection',
            name='client_ip',
            field=models.GenericIPAddressField(verbose_name='IP клиента'),
        ),
        migrations.AlterField(
            model_name='activeconnection',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_connection', to='api.vpsserver'),
        ),
        migrations.AlterField(
            model_name='activeconnection',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_connection', to='api.proxytoken'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='busy_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Занят с'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='connection_method',
            field=models.CharField(default='HTTP-прокси с аутентификацией', max_length=100, verbose_name='Способ подключения'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.56.105', verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='proxy_password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='proxy_port',
            field=models.IntegerField(default=3128, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Порт прокси'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='proxy_username',
            field=models.CharField(default='username', max_length=50, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('busy', 'Занят'), ('error', 'Ошибка'), ('maintenance', 'Обслуживание')], default='free', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='total_connections',
            field=models.IntegerField(default=0, verbose_name='Всего подключений'),
        ),
        migrations.AlterField(
            model_name='vpsserver',
            name='total_time_seconds',
            field=models.IntegerField(default=0, verbose_name='Общее время работы (сек)'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен подтверждения',
                'verbose_name_plural': 'Токены подтверждения',
            },
        ),
    ]
